CREATE DATABASE IF NOT EXISTS my_database;
USE my_database;

CREATE TABLE Customer (
    Customer_ID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) UNIQUE NOT NULL,
    Mobile_No VARCHAR(8) NOT NULL
);
