
DROP TABLE IF EXISTS scheduling;


CREATE TABLE IF NOT EXISTS scheduling (
  Schedule_ID INT NOT NULL AUTO_INCREMENT,
  ScheduleName VARCHAR(255) NOT NULL,
  ScheduleDateTime DATETIME NOT NULL,
  WeatherCheck BOOLEAN NOT NULL,
  PickUpLocation INT NOT NULL,
  DeliveryLocation INT NOT NULL,
  DroneID INT NOT NULL,
  PRIMARY KEY (Schedule_ID),
  FOREIGN KEY (PickUpLocation) REFERENCES Store(store_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (DeliveryLocation) REFERENCES Order(Order_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (DroneID) REFERENCES drone(DroneID)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
